# Workflow name
name: Backend Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: udacity
    steps:
      - name: Checkout code Backend
        uses: actions/checkout@v3
      
      - name: Set up Python Backend
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipenv Backend
        working-directory: ./starter/backend
        run: pip install pipenv 

      - name: Install dependencies Backend
        working-directory: ./starter/backend
        run: pipenv install  --deploy --dev

      - name: Lint code Backend
        working-directory: ./starter/backend
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code Backend
        uses: actions/checkout@v3
      
      - name: Set up Python Backend
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pipenv Backend
        working-directory: ./starter/backend
        run: pip install pipenv

      - name: Install dependencies Backend
        working-directory: ./starter/backend
        run: pipenv install

      - name: Run tests Backend
        working-directory: ./starter/backend
        run: pipenv run test

  build:
    needs: [lint, test]
    environment: udacity
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code Backend
        uses: actions/checkout@v3

      - name: Set up Docker Buildx Backend
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image Backend
        working-directory: ./starter/backend
        run: docker build . -t my-backend-app